version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app/app
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: serve -s build -l 3000
    expose:
      - "3000"
